import os

debug = ARGUMENTS.get( 'debug', 0 )

Export( 'common_env' )

model_objs = SConscript('../../../models/fodet/SConscript')
tools_objs = SConscript('../../../tools/SConscript')
python_objs = SConscript('../../../python/fodet/SConscript')
parsing_objs = SConscript('src/SConscript')

common_enf.SharedLibrary( 'aptk.so', parsing_objs + model_objs + python_objs + tools_objs ) 
